### ISSUE TITLE
Use in RequireJS

### ISSUE THREAD

**Issue by MaybeELEMENT** [newcat/baklavajs#235]
How can I use BaklavaJS in RequireJS? Cause everytime i try to create custom node, i get this:
```
Illegal constructor
    at new MathNode (nodes.js:8:9)
    at run.js:64:41
```
I think it have the same class name with typescript's node so i can't use it.
Because of that, i tried doing this:
```js
const bjs = require("@baklavajs/core")
class MathNode extends bjs.Node {

    type = "MathNode";
    name = "Math";

    constructor() {
        super();
        this.addInputInterface("Number 1", "NumberOption", 1);
        this.addInputInterface("Number 2", "NumberOption", 10);
        this.addOutputInterface("Output");
        this.addOption("Operation", "SelectOption", {
            selected: "Add",
            items: [ "Add", "Subtract" ]
        });
    }

    calculate() {
        const n1 = this.getInterface("Number 1").value;
        const n2 = this.getInterface("Number 2").value;
        const operation = this.getOptionValue("Operation").selected;
        let result;
        if (operation === "Add") {
            result = n1 + n2;
        } else if (operation === "Subtract") {
            result = n1 - n2;
        }
        this.getInterface("Output").value = result;
    }

}
```
i get this error:
```
TypeError: nt is not a constructor
    at EditorView.onContextMenuClick (index.js:7339:55)
    at Be (vue.min.js:6:11394)
    at a.n (vue.min.js:6:13178)
    at Be (vue.min.js:6:11394)
    at e.$emit (vue.min.js:6:34446)
    at ContextMenu.onChildClick (index.js:6947:14)
    at Be (vue.min.js:6:11394)
    at a.n (vue.min.js:6:13178)
    at Be (vue.min.js:6:11394)
    at e.$emit (vue.min.js:6:34446)
  | Ve | @ | vue.min.js:6
-- | -- | -- | --
  | Ue | @ | vue.min.js:6
  | He | @ | vue.min.js:6
  | Be | @ | vue.min.js:6
  | n | @ | vue.min.js:6
  | Be | @ | vue.min.js:6
  | e.$emit | @ | vue.min.js:6
  | ContextMenu.onChildClick | @ | index.js:6947
  | Be | @ | vue.min.js:6
  | n | @ | vue.min.js:6
  | Be | @ | vue.min.js:6
  | e.$emit | @ | vue.min.js:6
  | ContextMenu.onClick | @ | index.js:6942
  | click | @ | index.js:5555
  | Be | @ | vue.min.js:6
  | n | @ | vue.min.js:6
  | Qr.o._wrapper | @ | vue.min.js:6
```
I've been working on this for like 2 hours already, please tell me how to fix it.

**Comment by newcat** [comment]
Could be an issue with RequireJS, I have never worked with that. How did you register the node type in the editor?

**Comment by MaybeELEMENT** [comment]
> Could be an issue with RequireJS, I have never worked with that. How did you register the node type in the editor?

i use NodeBuilder to build a Node

**Comment by MaybeELEMENT** [comment]
> Could be an issue with RequireJS, I have never worked with that. How did you register the node type in the editor?

@newcat Can you accept my discord request? My discord: /Lucas#4733
